import type { Database, Expense } from "./types";

const now = "2026-08-28T14:20:00.000Z";

function expense(partial: Expense): Expense {
  return partial;
}

export const SEED: Database = {
  companies: [
    {
      id: "cmp_concept",
      name: "ROM Concept",
      legal_name: "ROM Concept Ltda",
      slug: "rom-concept",
      initials: "RC",
      color: "#6366F1",
      is_active: true,
    },
    {
      id: "cmp_servicos",
      name: "ROM Serviços",
      legal_name: "ROM Serviços Ltda",
      slug: "rom-servicos",
      initials: "RS",
      color: "#10B981",
      is_active: true,
    },
    {
      id: "cmp_logistica",
      name: "ROM Logística",
      legal_name: "ROM Logística Ltda",
      slug: "rom-logistica",
      initials: "RL",
      color: "#F59E0B",
      is_active: true,
    },
    {
      id: "cmp_digital",
      name: "ROM Digital",
      legal_name: "ROM Digital Ltda",
      slug: "rom-digital",
      initials: "RD",
      color: "#EC4899",
      is_active: true,
    },
  ],
  categories: [
    { id: "cat_viagem", name: "Viagem", color: "#6366F1", is_active: true },
    { id: "cat_alim", name: "Alimentação", color: "#F59E0B", is_active: true },
    { id: "cat_esc", name: "Escritório", color: "#EC4899", is_active: true },
    { id: "cat_soft", name: "Software", color: "#10B981", is_active: true },
    { id: "cat_outros", name: "Outros", color: "#71717A", is_active: true },
  ],
  users: [
    {
      id: "usr_adm",
      name: "Adriana Martins",
      email: "adm@romconcept.com.br",
      password: "demo",
      role: "admin",
      status: "active",
      companyIds: ["cmp_concept", "cmp_servicos", "cmp_logistica", "cmp_digital"],
      created: "2026-01-10T12:00:00.000Z",
    },
    {
      id: "usr_fin",
      name: "Carlos Ferreira",
      email: "financeiro@romconcept.com.br",
      password: "demo",
      role: "financeiro",
      status: "active",
      companyIds: ["cmp_concept", "cmp_servicos", "cmp_logistica", "cmp_digital"],
      created: "2026-02-04T12:00:00.000Z",
    },
    {
      id: "usr_ana",
      name: "Ana Souza",
      email: "ana@romconcept.com.br",
      password: "demo",
      role: "solicitante",
      status: "active",
      companyIds: ["cmp_concept", "cmp_digital"],
      created: "2026-03-12T12:00:00.000Z",
    },
    {
      id: "usr_pedro",
      name: "Pedro Lima",
      email: "pedro@romconcept.com.br",
      password: "demo",
      role: "solicitante",
      status: "active",
      companyIds: ["cmp_servicos", "cmp_logistica"],
      created: "2026-04-01T12:00:00.000Z",
    },
    {
      id: "usr_lia",
      name: "Lia Albuquerque",
      email: "lia@romconcept.com.br",
      password: "demo",
      role: "solicitante",
      status: "inactive",
      companyIds: ["cmp_concept"],
      created: "2026-05-18T12:00:00.000Z",
    },
  ],
  invitations: [
    {
      id: "inv_joao",
      email: "joao@romconcept.com.br",
      role: "solicitante",
      companyIds: ["cmp_concept"],
      token: "convite-demo-joao",
      invitedBy: "usr_adm",
      created: "2026-08-20T09:00:00.000Z",
      expires: "2026-09-20T09:00:00.000Z",
      accepted: false,
    },
  ],
  expenses: [
    expense({
      id: "exp_aws",
      title: "Renovação anual AWS",
      description: "Infraestrutura de produção e ambiente de homologação do ROM Flow.",
      expense_type: "fornecedor",
      event_project: "Plataforma 2026",
      amount: 12840,
      category: "Software",
      payment_method: "pix",
      beneficiary_name: "Amazon Web Services Brasil",
      beneficiary_document: "15.436.940/0001-03",
      pix_key: "15.436.940/0001-03",
      bank_name: "",
      agency: "",
      account: "",
      boleto_code: "",
      max_payment_date: "2026-09-05",
      receipt_justification: "",
      receipt: {
        name: "nf-aws-2026.pdf",
        size: 240_000,
        type: "application/pdf",
        dataUrl: "",
      },
      payment_proof: null,
      company: "cmp_concept",
      requester: "usr_ana",
      approver: "usr_fin",
      status: "em_analise",
      scheduled_date: null,
      review_note: "",
      created: "2026-08-22T11:10:00.000Z",
      updated: now,
    }),
    expense({
      id: "exp_viagem",
      title: "Passagens SP → Recife",
      description: "Deslocamento da equipe comercial para reunião com cliente estratégico.",
      expense_type: "reembolso",
      event_project: "Roadshow Nordeste",
      amount: 3640.9,
      category: "Viagem",
      payment_method: "ted",
      beneficiary_name: "Ana Souza",
      beneficiary_document: "412.908.221-00",
      pix_key: "",
      bank_name: "Nubank",
      agency: "0001",
      account: "918273-4",
      boleto_code: "",
      max_payment_date: "2026-09-02",
      receipt_justification: "",
      receipt: {
        name: "e-tickets.pdf",
        size: 180_000,
        type: "application/pdf",
        dataUrl: "",
      },
      payment_proof: null,
      company: "cmp_concept",
      requester: "usr_ana",
      approver: null,
      status: "enviada",
      scheduled_date: null,
      review_note: "",
      created: "2026-08-26T16:40:00.000Z",
      updated: "2026-08-26T16:40:00.000Z",
    }),
    expense({
      id: "exp_alim",
      title: "Coffee com investidores",
      description: "Café da manhã para reunião de governança no escritório da Faria Lima.",
      expense_type: "fornecedor",
      event_project: "Board Q3",
      amount: 890.5,
      category: "Alimentação",
      payment_method: "pix",
      beneficiary_name: "Padaria da Vila",
      beneficiary_document: "22.109.333/0001-88",
      pix_key: "contato@padariadavila.com.br",
      bank_name: "",
      agency: "",
      account: "",
      boleto_code: "",
      max_payment_date: "2026-08-30",
      receipt_justification: "",
      receipt: {
        name: "nf-coffee.jpg",
        size: 90_000,
        type: "image/jpeg",
        dataUrl: "",
      },
      payment_proof: null,
      company: "cmp_concept",
      requester: "usr_ana",
      approver: "usr_fin",
      status: "aprovada",
      scheduled_date: null,
      review_note: "",
      created: "2026-08-18T09:12:00.000Z",
      updated: "2026-08-25T10:00:00.000Z",
    }),
    expense({
      id: "exp_office",
      title: "Mobiliário sala de reuniões",
      description: "Mesa e cadeiras para a nova sala de governança.",
      expense_type: "fornecedor",
      event_project: "HQ São Paulo",
      amount: 7420,
      category: "Escritório",
      payment_method: "boleto",
      beneficiary_name: "Tok&Stok Corporativo",
      beneficiary_document: "61.585.865/0001-51",
      pix_key: "",
      bank_name: "",
      agency: "",
      account: "",
      boleto_code: "23793.38128 60007.827136 95000.063305 1 12340000742000",
      max_payment_date: "2026-09-08",
      receipt_justification: "",
      receipt: {
        name: "pedido-tokstok.pdf",
        size: 310_000,
        type: "application/pdf",
        dataUrl: "",
      },
      payment_proof: null,
      company: "cmp_concept",
      requester: "usr_adm",
      approver: "usr_fin",
      status: "agendada",
      scheduled_date: "2026-09-04",
      review_note: "",
      created: "2026-08-12T13:00:00.000Z",
      updated: "2026-08-24T18:20:00.000Z",
    }),
    expense({
      id: "exp_figma",
      title: "Licenças Figma Organization",
      description: "Assinatura anual do time de produto e design.",
      expense_type: "fornecedor",
      event_project: "Design System",
      amount: 1980,
      category: "Software",
      payment_method: "pix",
      beneficiary_name: "Figma Inc",
      beneficiary_document: "00.000.000/0001-00",
      pix_key: "billing@figma.com",
      bank_name: "",
      agency: "",
      account: "",
      boleto_code: "",
      max_payment_date: "2026-08-20",
      receipt_justification: "",
      receipt: {
        name: "invoice-figma.pdf",
        size: 88_000,
        type: "application/pdf",
        dataUrl: "",
      },
      payment_proof: {
        name: "comprovante-figma.pdf",
        size: 64_000,
        type: "application/pdf",
        dataUrl: "",
      },
      company: "cmp_concept",
      requester: "usr_ana",
      approver: "usr_fin",
      status: "paga",
      scheduled_date: "2026-08-15",
      review_note: "",
      created: "2026-08-02T08:40:00.000Z",
      updated: "2026-08-15T17:00:00.000Z",
    }),
    expense({
      id: "exp_docs",
      title: "Treinamento de compliance",
      description: "Workshop interno de governança e trilha de auditoria.",
      expense_type: "outros",
      event_project: "Compliance 2026",
      amount: 4500,
      category: "Outros",
      payment_method: "pix",
      beneficiary_name: "Instituto Ética corporativa",
      beneficiary_document: "09.221.100/0001-77",
      pix_key: "09.221.100/0001-77",
      bank_name: "",
      agency: "",
      account: "",
      boleto_code: "",
      max_payment_date: "2026-09-12",
      receipt_justification: "",
      receipt: null,
      payment_proof: null,
      company: "cmp_concept",
      requester: "usr_ana",
      approver: "usr_fin",
      status: "aguardando_documentacao",
      scheduled_date: null,
      review_note: "Anexar nota fiscal e lista de participantes antes da aprovação.",
      created: "2026-08-21T15:33:00.000Z",
      updated: "2026-08-27T11:12:00.000Z",
    }),
    expense({
      id: "exp_reject",
      title: "Patrocínio evento externo",
      description: "Cota de patrocínio em feira sem alinhamento com o plano anual.",
      expense_type: "outros",
      event_project: "Marketing",
      amount: 12000,
      category: "Outros",
      payment_method: "ted",
      beneficiary_name: "Expo Retail Brasil",
      beneficiary_document: "44.221.009/0001-10",
      pix_key: "",
      bank_name: "Itaú",
      agency: "1500",
      account: "00321-8",
      boleto_code: "",
      max_payment_date: "2026-08-25",
      receipt_justification: "",
      receipt: {
        name: "proposta.pdf",
        size: 120_000,
        type: "application/pdf",
        dataUrl: "",
      },
      payment_proof: null,
      company: "cmp_concept",
      requester: "usr_ana",
      approver: "usr_fin",
      status: "recusada",
      scheduled_date: null,
      review_note: "Fora do orçamento de marketing do trimestre.",
      created: "2026-08-08T10:00:00.000Z",
      updated: "2026-08-11T09:40:00.000Z",
    }),
    expense({
      id: "exp_serv",
      title: "Uniformes operacionais",
      description: "Kit de uniformes para a equipe de campo.",
      expense_type: "fornecedor",
      event_project: "Operações",
      amount: 2760,
      category: "Escritório",
      payment_method: "boleto",
      beneficiary_name: "Confecções Norte",
      beneficiary_document: "33.100.222/0001-55",
      pix_key: "",
      bank_name: "",
      agency: "",
      account: "",
      boleto_code: "34191.79001 01043.510047 91020.150008 8 12340000276000",
      max_payment_date: "2026-09-10",
      receipt_justification: "",
      receipt: {
        name: "nf-uniformes.pdf",
        size: 150_000,
        type: "application/pdf",
        dataUrl: "",
      },
      payment_proof: null,
      company: "cmp_servicos",
      requester: "usr_pedro",
      approver: null,
      status: "enviada",
      scheduled_date: null,
      review_note: "",
      created: "2026-08-27T12:10:00.000Z",
      updated: "2026-08-27T12:10:00.000Z",
    }),
  ],
  auditLogs: [
    {
      id: "aud_1",
      user: "usr_ana",
      action: "CREATE_EXPENSE",
      resource: "exp_aws",
      before: "—",
      after: "enviada",
      created: "2026-08-22T11:10:00.000Z",
    },
    {
      id: "aud_2",
      user: "usr_fin",
      action: "START_REVIEW",
      resource: "exp_aws",
      before: "enviada",
      after: "em_analise",
      created: "2026-08-22T15:02:00.000Z",
    },
    {
      id: "aud_3",
      user: "usr_fin",
      action: "APPROVE_EXPENSE",
      resource: "exp_alim",
      before: "em_analise",
      after: "aprovada",
      created: "2026-08-25T10:00:00.000Z",
    },
    {
      id: "aud_4",
      user: "usr_fin",
      action: "PAY_EXPENSE",
      resource: "exp_figma",
      before: "agendada",
      after: "paga",
      created: "2026-08-15T17:00:00.000Z",
    },
    {
      id: "aud_5",
      user: "usr_fin",
      action: "REJECT_EXPENSE",
      resource: "exp_reject",
      before: "em_analise",
      after: "recusada",
      created: "2026-08-11T09:40:00.000Z",
    },
    {
      id: "aud_6",
      user: "usr_fin",
      action: "REQUEST_DOCUMENTATION",
      resource: "exp_docs",
      before: "em_analise",
      after: "aguardando_documentacao",
      created: "2026-08-27T11:12:00.000Z",
    },
  ],
};
